#### BOW,TFIDF,Machine Learning Algorithms

Below is incorrect way , as we do test and train split after bow and tfidf creations 
1. Preprocessing And Cleaning (features Engineering)
2. BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
3. Train Test Split 
4. Trained Our Models

Correct way to do NLP
1. Preprocessing And Cleaning (features Engineering)
2. Train Test Split
3. BOW And TF-IDF (Sentences--->vectors) by doing this way we Preventing Data Leakage as model don't have any bit info about test data
4. Trained Our Models

In [2]:
import pandas as pd
messages=pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [3]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
# import nltk
# nltk.download('stopwords')

import os
import nltk

# Define the local directory in your current project folder
local_nltk_dir = os.path.join(os.getcwd(), 'nltk_data')

# Download stopwords to the local folder
nltk.download('stopwords', download_dir=local_nltk_dir)

# Ensure NLTK searches this local directory
if local_nltk_dir not in nltk.data.path:
    nltk.data.path.append(local_nltk_dir)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/abhishek/Documents/Complete-Data-Science-With-
[nltk_data]     Machine-Learning-And-NLP-2024-main/26-CompleteNLP For
[nltk_data]     Machine Learning/Practicals/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
## Data Cleaning And Preprocessing
import re
# import nltk
# nltk.download('stopwords')

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [7]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

## Test and Train Split

In [17]:
## Output Features
y=pd.get_dummies(messages['label']) # label:  spam/ham is output

In [18]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [19]:
y=y.iloc[:,0].values # either ham or spam can be used as output feature ,so lets takes 0th ham as output

In [20]:
y.shape

(5572,)

In [34]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [35]:
len(X_train),len(y_train)

(4457, 4457)

In [36]:
X_train

['long fuckin showr',
 'hot live fantasi call p per min ntt ltd po box croydon cr wb k',
 'get readi lt gt inch pleasur',
 'ok give minut think see btw alibi cut hair whole time',
 'check choos babe video sm shsex netun fgkslpopw fgkslpo',
 'waaaat lololo ok next time',
 '',
 'ye rent expens way save',
 'hai ana tomarrow come morn lt decim gt ill sathi go rto offic repli came home',
 'pl pl send mail know rel come deliv know cost risk benefit anyth els thank',
 'love u babe r u sure everyth alrit idiot txt bak girli',
 'ok feel like john lennon',
 'sweet heart',
 'god bless get good sleep dear pray',
 'walk mom right stagwood pass right winterston left victor hill address lt gt',
 'mom want know',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'captain room',
 'oh ok prob',
 'pleas call amanda regard renew upgrad current mobil handset free charg offer end today tel subject c',
 'ps u ur grown right',
 'fetch yun u fetch',
 'late call tomorrow morn take care sweet dream u ummifi bye',
 'latest g still scroung ammo want give new ak tri',
 'oh shit thought trip loooooool make much sens grin sofa refer sleep couch link sent went trip oh babe go celebr rent',
 'sac score big hundr set batsman',
 'da birthdat certif april real date today dont publish shall give special treat keep secret way thank wish',
 'arun u transfr amt',
 'call da wait call',
 'feb lt gt love u day send di ur valu frnd evn come back u gt marri person u luv u ignor di u lose ur luv evr',
 'oh get paid outstand one commerci hasbro august made us jump mani hoop get paid still',
 'wot u thout u gonna call txt bak luv k',
 'gd got free ice cream oso wan',
 'simpli sit watch match offic',
 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p',
 'poyyarikatur kolathupalayam unjalur post erod di lt gt',
 'hey boy want hot xxx pic sent direct ur phone txt porn hr free p per day stop text stopbcm sf wc n xx',
 'urgent mobil number award prize guarante call land line claim valid hr',
 'wondar full flim',
 'sorri call later meet',
 'think mentor percent sure',
 'hello boytoy made home constant thought love hope nice visit wait till come home kiss',
 'yo there class tmrw right',
 'anyth lor juz us lor',
 'call send girl erot ecstaci p min stop text call nat rate',
 'long take get',
 'holi live christ take long',
 'joy father john john ____ joy father u an th hav lt gt iq ti ia question tri answer',
 'yo call get chanc friend mine want ask big order',
 'say hi get ass back south tampa prefer kegger',
 'girl mani local u r virgin r readi fil ur everi sexual need u fil text cute p',
 'new club dont fink met yet b gr c u pleas leav msg day wiv ur area repli promis carli x call minmobsmor lkpobox hp fl',
 'home also',
 'hey next sun basic yoga cours bugi go pilat intro next sat tell time r free',
 'hous e sky quit dark liao rain got excus run alreadi rite hee',
 'buzz hey love think hope day goe well sleep miss babe long moment togeth love smile',
 'pen thing beyond joke wont biro master ever',
 'gokila talk aha',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'pleas attend phone',
 'dude sux snake got old raiden got buff',
 'perform award calcul everi two month current one month period',
 'mine like fr china noisi',
 'dont use hook',
 'sorri text amp drive coher see twenti',
 'happi birthday dear lot love rakhesh nri',
 'urgent urgent free flight europ give away call b th sept take friend free call claim ba nnfwfli ppm',
 'check audrey statu right',
 'yo gonna still stock tomorrow today tri get dubsack',
 'much got clean',
 'r u still work',
 'sorri call later',
 'take part mobil survey yesterday text use howev wish get txt send txt c www txt com p',
 'alrit hunni wot u nite didnt end goin town ju da pub instead ju chillin da mo bedroom love jen xxx',
 'guarante cash prize claim yr prize call custom servic repres pm',
 'heard u call night knicker make beg like u last time xx luv nikiyu net',
 'arm fine cardiff uni',
 'reali sorri recognis number confus r u pleas',
 'lick everi drop readi use mouth well',
 'sunshin quiz wkli q win top soni dvd player u know countri liverpool play mid week txt ansr sp tyron',
 'photoshop make comput shut',
 'haha get use drive usf man know lot stoner',
 'wot u wanna missi',
 'fantasi footbal back tv go sky gamestar sky activ play k dream team score start saturday regist sky opt',
 'borrow ur bag ok',
 'wuld without babi thought alon mite break wanna go crazi everyboy need ladi xxxxxxxx',
 'play one day last year know even though good team like india',
 'done',
 'boytoy miss happen',
 'lol knew saw dollar store',
 'get garden readi summer free select summer bulb seed worth scotsman saturday stop go notxt co uk',
 'u secret admir look make contact u find r reveal think ur special call',
 'wanna get laid nite want real dog locat sent direct ur mobil join uk largest dog network txt park nyt ec lp msg',
 'also sorta blown coupl time recent id rather text blue look weed',
 'sorri im get feel realli bad total reject kinda thing',
 'annoy',
 'sorri left phone upstair ok might hectic would bird one fell swoop date',
 'hope enjoy game yesterday sorri touch pl know fondli bein thot great week abiola',
 'time',
 'kalli dismissi nd test',
 'necessarili expect done get back though headin',
 'k give back thank',
 'great day beauti one',
 'home',
 'call u done',
 'reason team budget avail last buy unsold player base rate',
 'honeybe said sweetest world god laugh amp said wait u havnt met person read msg moral even god crack joke gm gn ge gn',
 'haha okay today weekend leh',
 'sorri u unsubscrib yet mob offer packag min term week pl resubmit request expiri repli themob help info',
 'see half hour',
 'cant pick phone right pl send messag',
 'someon u know ask date servic contact cant guess call reveal po box wu',
 'boooo alway work quit',
 'yup thk r e teacher said make face look longer darren ask cut short',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'lost kilo today',
 'hiya last night naughti bought cloth littl readi shop tho kind time wanna meet',
 'weightloss girl friend make load money ebay someth give thank god',
 'hi u want join st later meet five call u class',
 'work mon thur sat cant leh book liao day u free',
 'one best dialogu cute reltnship wen die dont come near bodi bcoz hand may come wipe ur tear time gud ni',
 'guy close',
 'antha num corrct dane',
 'shb b ok lor thanx',
 'omg could snow tonit',
 'lara said loan lt gt',
 'today sunday sunday holiday work',
 'depend qualiti want type sent boy fade glori want ralph mayb',
 'serious tell exact word right',
 'good r u work',
 'cough noth',
 'come home dinner',
 'happi babe woo hoo parti dude',
 'bold lt gt',
 'wors use half way stop better complet',
 'goodmorn today late hr back pain',
 'sweetheart hope kind day one load reason smile biola',
 'parent kidz friend n colleagu scream surpris wait sofa nake',
 'india win level seri mean record',
 'ha us e thing got tv watch u thk go tonight u alreadi haf smth mind',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'sign matur start say big thing actual start understand small thing nice even bslvyl',
 'oh grand bit parti mention cover charg probabl first come first serv',
 'life all mone eppolum oru pole allalo',
 'well im computerless time make oreo truffl',
 'done sorri hope next space give everyth want rememb furnitur around move lock lock leav key jenn',
 'escap theatr go watch kavalan minut',
 'great trip india bring light everyon project everyon lucki see smile bye abiola',
 'still mayb leav credit card get ga get back like told',
 'also chat awesom make regular unless see person',
 'tot group mate lucki havent repli wat time need leav',
 'hi kate u give ring asap xxx',
 'tell tell one treat hi hi hi',
 'problem spend lot qualiti time togeth',
 'mani happi return day wish happi birthday',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'hmm mani unfortun pic obvious arent hot cake kinda fun tho',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 'strang watch nd one bed sweet dream miss u',
 'sm auction brand new nokia auction today auction free join take part txt nokia',
 'call ok said call',
 'oh phone phone disconnect',
 'urgent mobil xxx bonu caller prize nd attempt reach call asap box n qp ppm',
 'ok',
 'sorri pa dont knw ru pa',
 'ful song lyric',
 'dun need use dial juz open da browser n surf',
 'tell friend plan valentin day lt url gt',
 'shower babi',
 'u secret admir reveal think u r special call opt repli reveal stop per msg recd cust care',
 'u think girl propos u today se ur bloodi funki shit fuck face asssssholeee',
 'oop lt gt',
 'go thru differ feel waver decis cope individu time heal everyth believ',
 'u',
 'vote wherev heart guid',
 'guess pub im im happi pig clover whatev say',
 'hello madam',
 'staff scienc nu edu sg phyhcmk teach pc',
 'call later network urgnt sm',
 'dunno close oredi v fan',
 'tmr brin lar aiya later come n c lar mayb neva set properli got da help sheet wif',
 'onum ela pa normal',
 'oh half hour much longer syria canada eh wow must get much work done day us extra time grin',
 'worri though understand import put place poorli thought punish face worst thing ever happen brb gonna go kill',
 'diet ate mani slice pizza yesterday ugh alway diet',
 'room',
 'pl send compani name saibaba colani',
 'last thing ever want hurt think would laugh embarass delet tag keep go far knew even fact even felt like would hurt show realli know messi wednesday bad problem time clean choos skype take pictur sleep want go mind thing make bed throw laundri top friend hous embarass underwear bra strewn bed pillow floor someth els use good least make bed',
 'sorri call later',
 'haha better late ever way could swing',
 'ha ha nan yalrigu heltini iyo kothi chikku u share mani thing wit far told bodi even utter word abt u ur trust much tell other plz nxt time dont use word ok chikku b',
 'finish miss plenti',
 'alrit jod how revis goin keri bin doin smidgin n e way u wanna cum colleg xx',
 'ya nice readi thursday',
 'shall fine avalarr hollalat',
 'one teach ship car',
 'place man',
 'hey sexi bun day word morn ym think',
 'come home class right need work shower',
 'get worri derek taylor alreadi assum worst',
 'dont know jabo abi',
 'haiyoh mayb hamster jealou million',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chang window logoff sound',
 'call get chanc plz lt',
 'ye princess want make happi',
 'cool like swim pool jacuzzi hous',
 'reach alreadi',
 'shall come get pickl',
 'dice art class thru thank though idea time come tomorrow',
 'gettin rdi ship comp',
 'thank da thangam feel happi dear also miss da',
 'haha cant tmr forfeit haha',
 'yup shd haf ard page add figur got mani page',
 'hi b ard christma enjoy n merri x ma',
 'cant pick phone right pl send messag',
 'ju finish avatar nigro',
 'actual send remind today wonder weekend',
 'sexi sexi cum text im wet warm readi porn u fun msg free recd msg p inc vat cancel text stop',
 'sorri bathroom sup',
 'sound great home',
 'will go app class',
 'alway braini one',
 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppmmobilesvari max',
 'fyi take quick shower epsilon like lt gt min',
 'pl call da happen',
 'ye realli great bhaji told kalli best cricket sachin world tough get',
 'ya one slow poo',
 'send print out da',
 'ok',
 'u secret admir look make contact u find r reveal think ur special call',
 'ask u meet da ge tmr nite',
 'mani peopl seem special first sight remain special till last sight maintain till life end take cr da',
 'messag sent askin lt gt dollar shoul pay lt gt lt gt',
 'want insid everi night',
 'ok much though h friday cant wait dunno wot hell im gonna anoth week becom slob oh wait alreadi done',
 'get lion england tone repli lionm mono lionp poli go www rington co uk origin n best tone gbp network oper rate appli',
 'uncl timi help clear car',
 'b floppi b snappi happi gay chat servic photo upload call p min stop text call',
 'hey come onlin use msn',
 'still chanc search hard get let tri',
 'gimm lt gt minut ago',
 'yeh def someth sat got pay day havbeen given pay rise work havebeen made preschoolco ordin feelingood luv',
 'yet chikku wat abt u',
 'good morn boytoy yummi lip sexi bun think crave need',
 'yar tot u knew di would happen long ago alreadi',
 'oh ho first time u use type word',
 'ju came back fr lunch wif si u leh',
 'still look car buy gone drive test yet',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'look like u wil b get headstart im leav bout ish u r desper compani could head earlier goin meet rummer',
 'oh yeah diet flew window',
 'hey project start aha da',
 'dare stupid wont tell anyth hear wont talk',
 'yeah tote u wanna',
 'shall book chez jule half eight ok',
 'ever green quot ever told jerri cartoon person irrit u alway one love u vri much fail express gud nyt',
 'new textbuddi chat horni guy ur area p free receiv search postcod gaytextbuddi com txt one name rpl stop cnl',
 'singl line big mean miss anyth ur best life miss ur best life anyth gud nyt',
 'freemsg fav xma tone repli real',
 'got fujitsu ibm hp toshiba got lot model say',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'ye princess go make moan',
 'oh k got job what',
 'cool want go kappa meet outsid mu',
 'wah oki oki muz make use e unlimit haha',
 'first time everyth',
 'day work day except saturday sunday',
 'import prevent dehydr give enough fluid',
 'search good dual sim mobil pa',
 'neva grumbl sad lor hee buy tmr lor aft lunch still meetin lunch tmr neva hear fr lei got lot work ar',
 'rather promin bite mark right cheek',
 'forgot tell smth like number section clearer',
 'k fyi back parent place south tampa might need deal somewher els',
 'said okay sorri',
 'mobil number pl sm ur mail id convey regard achan amma rakhesh qatar',
 'cant see join deni mina deni want alon time',
 'sad stori man last week b day wife nt wish parent forgot n kid went work even colleagu wish enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went said u mind go bedroom minut ok sed sexi mood came minut latr wid cake n wife parent kidz friend n colleagu scream surpris wait sofa nake',
 'cbe realli good nowaday lot shop showroom citi shape good',
 'hi darlin hope nice night wish come cant wait see love fran ps want dirti anal sex want man gang bang',
 'velli good ye pleas',
 'tri contact repli offer min textand new video phone call repli free deliveri tomorrow',
 'friend help us problem give stupid suggest land us anoth problem help us forgt previou problem',
 'u secret admir look make contact u find r reveal think ur special call stopsm ppm',
 'u doin babi girl hope u okay everi time call ure phone miss u get touch',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'horribl gal sch stuff come u got mc',
 'ya ok dinner',
 'dont know get messag',
 'gain right wife dont demand tri husband let see',
 'good night dear sleepwel amp take care',
 'privat account statement xxxxxx show un redeem point call identifi code expir',
 'cocksuck make feel better ipad worthless garbag novelti item feel bad even want one',
 'get ok',
 'go fool dont cheat other ok',
 'either way work lt gt year old hope doesnt bother',
 'good afternoon loverboy goe day luck come way think sweeti send love across sea make smile happi',
 'meet call later',
 'tonight mate catch sleep new number way',
 'carlo took leav minut',
 'know mallika sherawat yesterday find lt url gt',
 'cd u congratul ur award cd gift voucher gift guarante freeentri wkli draw xt music tnc www ldew com win ppmx age',
 'yar say got error',
 'met alex nichol middl school turn deal',
 'sir goodmorn free call',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'know god creat gap finger one made come amp fill gap hold hand love',
 'came look flat seem ok away alot wiv work got woman come',
 'love work home',
 'sad stori man last week b day wife nt wish parent forgot n kid went work even colleagu wish',
 'privat account statement show un redeem point call identifi code expir',
 'world happiest frnd never charact dey best understand differ',
 'probabl gonna swing wee bit',
 'think move lt gt week',
 'hmmm give one day',
 'misplac number send text old number wonder heard year best mcat got number atlanta friend',
 'never believ actual got taunton wow',
 'free st week entri textpod chanc win gb ipod cash everi wk txt pod ts cs www textpod net custcar',
 'thank talk saturday dear cherish brother role model',
 'prob hon u doinat mo',
 'hous maid murder coz man murder lt gt th januari public holiday govt instituit close includ post offic understand',
 'dai da send resum id',
 'im gonnamissu much would say il send u postcard butther abouta much chanc merememberin asther ofsi breakin contract luv yaxx',
 'number u live',
 'one day crab run sea shore wave came n clear footprint crab crab ask frnd r u clear beauti footprint wave repli fox follow ur footprint catch that clear frndsship never let u dwn gud nyt',
 'mean get door',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'wine flow never',
 'ok',
 'think get away trek long famili town sorri',
 'send someon els',
 'urgent call landlin complimentari tenerif holiday cash await collect sae cs box hp yf ppm',
 'freemsg month unlimit free call activ smartcal txt call subscriptn gbp wk unlimit call help stop txt stop landlineonli',
 'spoke uncl john today strongli feel need sacrific keep go call beg listen dont make promis make clear thing easi need pleas let us work thing long keep expect help creativ stifl pl keep happi promis part',
 'ok may free gym',
 'hi wlcome back wonder got eaten lion someth noth much',
 'sorri meet call later',
 'ye small kid boost secret energi',
 'world suffer lot violenc bad peopl silenc good peopl gud night',
 'small problem auction punj ask tiwari',
 'ye mum lookin strong',
 'say fantast chanc anyth need bigger life lift lose live think would first person die n v q',
 'puriti friendship two smile read forward messag smile see name gud evng',
 'hey what plan sat',
 'go write msg put dictionari mode cover screen hand press lt gt gentli remov ur hand interest',
 'went ganesh dress shop',
 'much dirti fellow',
 'yup',
 'wah lucki man save money hee',
 'take derek amp taylor walmart back time done leav mous desk text priscilla readi',
 'askd u question hour answer',
 'take mokka player',
 'probabl gonna see later tonight lt',
 'outsid offic take',
 'good find way',
 'hey sexi bun told ador loverboy hope rememb thank sister law meatbal grin love babe',
 'v nice sheffield tom air opinion categori b use measur ethnic next censu busi transcrib',
 'ok k sri knw siva tat askd',
 'final chanc claim ur worth discount voucher today text ye savamob member offer mobil cs savamob pobox uz sub',
 'fuck babe happen come never came back',
 'camera award sipix digit camera call fromm landlin deliveri within day',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'shall start hear',
 'alway chat fact need money rais',
 'sorri call later meet',
 'money steve mate',
 'way stay oh',
 'new messag pleas call',
 'havent still waitin usual come back sch oredi',
 'freemsg claim ur sm messag text ok use web mobil ur mate etc join txt com p wk c box la wu remov txtx stop',
 'say give call friend got money definit buy end week',
 'take like noon',
 'congrat kano whr treat maga',
 'home ard wat time u reach',
 'din tell u ju',

### Create Bag Of Words

In [37]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [38]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [39]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], shape=(4457, 2500))

In [40]:
cv.vocabulary_

{'long': np.int64(1168),
 'hot': np.int64(947),
 'live': np.int64(1150),
 'fantasi': np.int64(644),
 'call': np.int64(236),
 'per': np.int64(1531),
 'min': np.int64(1283),
 'ntt': np.int64(1441),
 'ltd': np.int64(1203),
 'po': np.int64(1589),
 'box': np.int64(197),
 'croydon': np.int64(436),
 'cr': np.int64(429),
 'wb': np.int64(2351),
 'hot live': np.int64(948),
 'live fantasi': np.int64(1151),
 'fantasi call': np.int64(645),
 'call per': np.int64(254),
 'per min': np.int64(1533),
 'min ntt': np.int64(1286),
 'ntt ltd': np.int64(1442),
 'ltd po': np.int64(1204),
 'po box': np.int64(1590),
 'box croydon': np.int64(198),
 'croydon cr': np.int64(437),
 'cr wb': np.int64(430),
 'get': np.int64(760),
 'readi': np.int64(1684),
 'lt': np.int64(1199),
 'gt': np.int64(846),
 'inch': np.int64(993),
 'pleasur': np.int64(1580),
 'get readi': np.int64(766),
 'lt gt': np.int64(1201),
 'gt inch': np.int64(848),
 'ok': np.int64(1461),
 'give': np.int64(779),
 'minut': np.int64(1292),
 'think': np.int64(2091),
 'see': np.int64(1798),
 'btw': np.int64(216),
 'cut': np.int64(454),
 'hair': np.int64(876),
 'whole': np.int64(2390),
 'time': np.int64(2117),
 'check': np.int64(321),
 'choos': np.int64(329),
 'babe': np.int64(123),
 'video': np.int64(2291),
 'sm': np.int64(1891),
 'next': np.int64(1409),
 'ye': np.int64(2474),
 'rent': np.int64(1713),
 'expens': np.int64(628),
 'way': np.int64(2348),
 'save': np.int64(1780),
 'hai': np.int64(875),
 'come': np.int64(370),
 'morn': np.int64(1335),
 'decim': np.int64(488),
 'ill': np.int64(983),
 'go': np.int64(787),
 'offic': np.int64(1455),
 'repli': np.int64(1717),
 'came': np.int64(265),
 'home': np.int64(933),
 'lt decim': np.int64(1200),
 'decim gt': np.int64(489),
 'pl': np.int64(1562),
 'send': np.int64(1812),
 'mail': np.int64(1222),
 'know': np.int64(1068),
 'deliv': np.int64(497),
 'cost': np.int64(418),
 'anyth': np.int64(67),
 'els': np.int64(580),
 'thank': np.int64(2080),
 'pl pl': np.int64(1567),
 'pl send': np.int64(1568),
 'anyth els': np.int64(68),
 'love': np.int64(1183),
 'sure': np.int64(2021),
 'everyth': np.int64(618),
 'alrit': np.int64(51),
 'idiot': np.int64(979),
 'txt': np.int64(2189),
 'bak': np.int64(131),
 'feel': np.int64(656),
 'like': np.int64(1134),
 'john': np.int64(1036),
 'feel like': np.int64(659),
 'sweet': np.int64(2027),
 'heart': np.int64(895),
 'sweet heart': np.int64(2029),
 'god': np.int64(802),
 'bless': np.int64(174),
 'good': np.int64(810),
 'sleep': np.int64(1886),
 'dear': np.int64(482),
 'pray': np.int64(1617),
 'walk': np.int64(2317),
 'mom': np.int64(1325),
 'right': np.int64(1739),
 'pass': np.int64(1519),
 'left': np.int64(1113),
 'address': np.int64(22),
 'want': np.int64(2326),
 'want know': np.int64(2330),
 'request': np.int64(1726),
 'mell': np.int64(1268),
 'set': np.int64(1834),
 'callertun': np.int64(262),
 'caller': np.int64(260),
 'press': np.int64(1622),
 'copi': np.int64(416),
 'friend': np.int64(724),
 'captain': np.int64(280),
 'room': np.int64(1750),
 'oh': np.int64(1458),
 'prob': np.int64(1636),
 'oh ok': np.int64(1460),
 'ok prob': np.int64(1466),
 'pleas': np.int64(1576),
 'regard': np.int64(1703),
 'current': np.int64(447),
 'mobil': np.int64(1310),
 'free': np.int64(704),
 'charg': np.int64(313),
 'offer': np.int64(1452),
 'end': np.int64(584),
 'today': np.int64(2133),
 'tel': np.int64(2055),
 'pleas call': np.int64(1577),
 'ur': np.int64(2234),
 'fetch': np.int64(663),
 'yun': np.int64(2496),
 'late': np.int64(1090),
 'tomorrow': np.int64(2142),
 'take': np.int64(2035),
 'care': np.int64(283),
 'dream': np.int64(552),
 'bye': np.int64(230),
 'take care': np.int64(2036),
 'sweet dream': np.int64(2028),
 'latest': np.int64(1094),
 'still': np.int64(1970),
 'new': np.int64(1400),
 'tri': np.int64(2167),
 'shit': np.int64(1846),
 'thought': np.int64(2103),
 'trip': np.int64(2172),
 'make': np.int64(1223),
 'much': np.int64(1360),
 'sens': np.int64(1822),
 'grin': np.int64(843),
 'sofa': np.int64(1908),
 'refer': np.int64(1702),
 'link': np.int64(1145),
 'sent': np.int64(1823),
 'went': np.int64(2379),
 'celebr': np.int64(304),
 'score': np.int64(1789),
 'big': np.int64(161),
 'da': np.int64(457),
 'april': np.int64(80),
 'real': np.int64(1685),
 'date': np.int64(467),
 'dont': np.int64(537),
 'shall': np.int64(1839),
 'special': np.int64(1939),
 'treat': np.int64(2165),
 'keep': np.int64(1052),
 'secret': np.int64(1796),
 'wish': np.int64(2403),
 'amt': np.int64(57),
 'wait': np.int64(2313),
 'feb': np.int64(654),
 'day': np.int64(469),
 'di': np.int64(507),
 'valu': np.int64(2286),
 'frnd': np.int64(732),
 'back': np.int64(126),
 'marri': np.int64(1241),
 'person': np.int64(1539),
 'luv': np.int64(1212),
 'ignor': np.int64(981),
 'lose': np.int64(1177),
 'day send': np.int64(477),
 'come back': np.int64(371),
 'paid': np.int64(1509),
 'one': np.int64(1477),
 'made': np.int64(1216),
 'us': np.int64(2273),
 'mani': np.int64(1234),
 'wot': np.int64(2435),
 'gonna': np.int64(809),
 'gd': np.int64(754),
 'got': np.int64(822),
 'ice': np.int64(974),
 'oso': np.int64(1500),
 'wan': np.int64(2319),
 'sit': np.int64(1876),
 'watch': np.int64(2345),
 'match': np.int64(1243),
 'eeri': np.int64(575),
 'nokia': np.int64(1423),
 'tone': np.int64(2143),
 'rpli': np.int64(1757),
 'titl': np.int64(2126),
 'eg': np.int64(576),
 'www': np.int64(2451),
 'getz': np.int64(772),
 'co': np.int64(351),
 'uk': np.int64(2209),
 'pobox': np.int64(1591),
 'wq': np.int64(2441),
 'nokia tone': np.int64(1428),
 'www getz': np.int64(2453),
 'getz co': np.int64(773),
 'co uk': np.int64(353),
 'uk pobox': np.int64(2212),
 'pobox wq': np.int64(1594),
 'post': np.int64(1606),
 'hey': np.int64(903),
 'boy': np.int64(200),
 'xxx': np.int64(2466),
 'pic': np.int64(1551),
 'direct': np.int64(520),
 'phone': np.int64(1545),
 'porn': np.int64(1603),
 'hr': np.int64(957),
 'stop': np.int64(1976),
 'text': np.int64(2065),
 'wc': np.int64(2352),
 'xx': np.int64(2465),
 'sent direct': np.int64(1824),
 'direct ur': np.int64(521),
 'ur phone': np.int64(2255),
 'per day': np.int64(1532),
 'stop text': np.int64(1984),
 'wc xx': np.int64(2353),
 'urgent': np.int64(2264),
 'number': np.int64(1444),
 'award': np.int64(114),
 'prize': np.int64(1631),
 'guarante': np.int64(857),
 'land': np.int64(1075),
 'line': np.int64(1141),
 'claim': np.int64(334),
 'valid': np.int64(2284),
 'urgent mobil': np.int64(2266),
 'mobil number': np.int64(1317),
 'number award': np.int64(1445),
 'award prize': np.int64(119),
 'prize guarante': np.int64(1634),
 'guarante call': np.int64(859),
 'call land': np.int64(246),
 'land line': np.int64(1076),
 'line claim': np.int64(1142),
 'claim valid': np.int64(340),
 'valid hr': np.int64(2285),
 'full': np.int64(735),
 'sorri': np.int64(1925),
 'later': np.int64(1091),
 'meet': np.int64(1263),
 'sorri call': np.int64(1926),
 'call later': np.int64(248),
 'later meet': np.int64(1092),
 'percent': np.int64(1537),
 'hello': np.int64(900),
 'boytoy': np.int64(201),
 'hope': np.int64(937),
 'nice': np.int64(1412),
 'visit': np.int64(2300),
 'till': np.int64(2116),
 'kiss': np.int64(1065),
 'hope nice': np.int64(942),
 'wait till': np.int64(2315),
 'come home': np.int64(373),
 'yo': np.int64(2492),
 'class': np.int64(341),
 'lor': np.int64(1175),
 'juz': np.int64(1048),
 'anyth lor': np.int64(69),
 'lor juz': np.int64(1176),
 'girl': np.int64(777),
 'rate': np.int64(1669),
 'min stop': np.int64(1287),
 'text call': np.int64(2067),
 'joy': np.int64(1042),
 'father': np.int64(651),
 'an': np.int64(58),
 'th': np.int64(2076),
 'hav': np.int64(890),
 'ti': np.int64(2109),
 'question': np.int64(1655),
 'answer': np.int64(63),
 'joy father': np.int64(1043),
 'chanc': np.int64(308),
 'mine': np.int64(1291),
 'ask': np.int64(93),
 'order': np.int64(1496),
 'call get': np.int64(244),
 'friend mine': np.int64(725),
 'say': np.int64(1782),
 'hi': np.int64(908),
 'ass': np.int64(98),
 'south': np.int64(1933),
 'tampa': np.int64(2040),
 'prefer': np.int64(1619),
 'say hi': np.int64(1783),
 'local': np.int64(1156),
 'everi': np.int64(611),
 'need': np.int64(1389),
 'cute': np.int64(455),
 'club': np.int64(348),
 'met': np.int64(1278),
 'yet': np.int64(2489),
 'gr': np.int64(833),
 'leav': np.int64(1109),
 'msg': np.int64(1349),
 'wiv': np.int64(2412),
 'area': np.int64(84),
 'promis': np.int64(1641),
 'hp': np.int64(956),
 'ur area': np.int64(2235),
 'also': np.int64(52),
 'sun': np.int64(2011),
 'basic': np.int64(137),
 'yoga': np.int64(2493),
 'cours': np.int64(425),
 'bugi': np.int64(222),
 'pilat': np.int64(1557),
 'sat': np.int64(1774),
 'tell': np.int64(2056),
 'hous': np.int64(951),
 'sky': np.int64(1883),
 'quit': np.int64(1657),
 'liao': np.int64(1126),
 'rain': np.int64(1663),
 'excus': np.int64(626),
 'run': np.int64(1761),
 'alreadi': np.int64(49),
 'rite': np.int64(1745),
 'hee': np.int64(897),
 'buzz': np.int64(227),
 'goe': np.int64(804),
 'well': np.int64(2375),
 'miss': np.int64(1295),
 'moment': np.int64(1326),
 'togeth': np.int64(2139),
 'smile': np.int64(1897),
 'goe well': np.int64(806),
 'miss babe': np.int64(1296),
 'thing': np.int64(2090),
 'joke': np.int64(1039),
 'wont': np.int64(2423),
 'ever': np.int64(610),
 'talk': np.int64(2039),
 'aha': np.int64(37),
 'geeee': np.int64(757),
 'woke': np.int64(2419),
 'bed': np.int64(149),
 'cuddl': np.int64(444),
 'attend': np.int64(104),
 'dude': np.int64(560),
 'old': np.int64(1474),
 'two': np.int64(2187),
 'month': np.int64(1331),
 'fr': np.int64(703),
 'use': np.int64(2275),
 'hook': np.int64(936),
 'amp': np.int64(56),
 'drive': np.int64(556),
 'happi': np.int64(884),
 'birthday': np.int64(165),
 'lot': np.int64(1180),
 'rakhesh': np.int64(1664),
 'happi birthday': np.int64(885),
 'birthday dear': np.int64(166),
 'lot love': np.int64(1181),
 'flight': np.int64(687),
 'away': np.int64(121),
 'sept': np.int64(1826),
 'ppm': np.int64(1613),
 'free call': np.int64(707),
 'call claim': np.int64(240),
 'stock': np.int64(1973),
 'tri get': np.int64(2170),
 'clean': np.int64(342),
 'work': np.int64(2425),
 'part': np.int64(1515),
 'yesterday': np.int64(2488),
 'howev': np.int64(954),
 'com': np.int64(367),
 'take part': np.int64(2037),
 'www txt': np.int64(2457),
 'hunni': np.int64(965),
 'nite': np.int64(1420),
 'didnt': np.int64(509),
 'goin': np.int64(807),
 'town': np.int64(2160),
 'ju': np.int64(1045),
 'pub': np.int64(1643),
 'instead': np.int64(1004),
 'mo': np.int64(1305),
 'jen': np.int64(1031),
 'cash': np.int64(289),
 'yr': np.int64(2495),
 'custom': np.int64(452),
 'servic': np.int64(1830),
 'repres': np.int64(1724),
 'pm': np.int64(1586),
 'guarante cash': np.int64(860),
 'cash prize': np.int64(294),
 'prize claim': np.int64(1633),
 'prize call': np.int64(1632),
 'call custom': np.int64(241),
 'custom servic': np.int64(453),
 'servic repres': np.int64(1833),
 'heard': np.int64(894),
 'night': np.int64(1415),
 'beg': np.int64(151),
 'last': np.int64(1085),
 'net': np.int64(1392),
 'arm': np.int64(87),
 'fine': np.int64(677),
 'uni': np.int64(2221),
 'reali': np.int64(1686),
 'confus': np.int64(394),
 'lick': np.int64(1128),
 'drop': np.int64(558),
 'sunshin': np.int64(2015),
 'quiz': np.int64(1658),
 'wkli': np.int64(2415),
 'win': np.int64(2396),
 'top': np.int64(2153),
 'soni': np.int64(1920),
 'dvd': np.int64(567),
 'player': np.int64(1575),
 'countri': np.int64(423),
 'play': np.int64(1572),
 'mid': np.int64(1279),
 'week': np.int64(2360),
 'sp': np.int64(1934),
 'sunshin quiz': np.int64(2016),
 'soni dvd': np.int64(1921),
 'week txt': np.int64(2366),
 'comput': np.int64(386),
 'haha': np.int64(873),
 'usf': np.int64(2278),
 'man': np.int64(1230),
 'wanna': np.int64(2325),
 'footbal': np.int64(694),
 'tv': np.int64(2185),
 'activ': np.int64(17),
 'team': np.int64(2050),
 'start': np.int64(1963),
 'saturday': np.int64(1776),
 'regist': np.int64(1704),
 'opt': np.int64(1490),
 'bag': np.int64(129),
 'without': np.int64(2411),
 'babi': np.int64(125),
 'alon': np.int64(48),
 'mite': np.int64(1301),
 'break': np.int64(205),
 'crazi': np.int64(432),
 'ladi': np.int64(1073),
 'year': np.int64(2484),
 'even': np.int64(608),
 'though': np.int64(2102),
 'india': np.int64(998),
 'one day': np.int64(1478),
 'done': np.int64(536),
 'happen': np.int64(883),
 'lol': np.int64(1165),
 'knew': np.int64(1067),
 'saw': np.int64(1781),
 'dollar': np.int64(535),
 'store': np.int64(1987),
 'summer': np.int64(2010),
 'select': np.int64(1806),
 'worth': np.int64(2433),
 'stop go': np.int64(1980),
 'admir': np.int64(23),
 'look': np.int64(1171),
 'contact': np.int64(401),
 'find': np.int64(672),
 'reveal': np.int64(1735),
 'secret admir': np.int64(1797),
 'admir look': np.int64(24),
 'look make': np.int64(1173),
 'make contact': np.int64(1225),
 'contact find': np.int64(403),
 'find reveal': np.int64(676),
 'reveal think': np.int64(1736),
 'think ur': np.int64(2097),
 'ur special': np.int64(2258),
 'special call': np.int64(1941),
 'laid': np.int64(1074),
 'dog': np.int64(532),
 'locat': np.int64(1157),
 'join': np.int64(1037),
 'largest': np.int64(1083),
 'network': np.int64(1395),
 'park': np.int64(1514),
 'nyt': np.int64(1449),
 'ec': np.int64(574),
 'lp': np.int64(1196),
 'get laid': np.int64(765),
 'want real': np.int64(2333),
 'locat sent': np.int64(1158),
 'ur mobil': np.int64(2251),
 'join uk': np.int64(1038),
 'uk largest': np.int64(2210),
 'largest dog': np.int64(1084),
 'dog network': np.int64(533),
 'nyt ec': np.int64(1450),
 'lp msg': np.int64(1197),
 'coupl': np.int64(424),
 'recent': np.int64(1696),
 'id': np.int64(975),
 'rather': np.int64(1672),
 'blue': np.int64(178),
 'weed': np.int64(2359),
 'im': np.int64(984),
 'realli': np.int64(1688),
 'bad': np.int64(128),
 'total': np.int64(2156),
 'kinda': np.int64(1063),
 'might': np.int64(1281),
 'would': np.int64(2436),
 'bird': np.int64(164),
 'enjoy': np.int64(591),
 'game': np.int64(744),
 'touch': np.int64(2157),
 'great': np.int64(837),
 'abiola': np.int64(2),
 'hope enjoy': np.int64(938),
 'great week': np.int64(839),
 'kalli': np.int64(1049),
 'nd': np.int64(1383),
 'test': np.int64(2064),
 'expect': np.int64(627),
 'get back': np.int64(761),
 'beauti': np.int64(146),
 'great day': np.int64(838),
 'reason': np.int64(1691),
 'budget': np.int64(221),
 'avail': np.int64(108),
 'buy': np.int64(226),
 'said': np.int64(1769),
 'world': np.int64(2428),
 'laugh': np.int64(1099),
 'read': np.int64(1682),
 'moral': np.int64(1334),
 'gm': np.int64(783),
 'gn': np.int64(785),
 'ge': np.int64(755),
 'gm gn': np.int64(784),
 'gn ge': np.int64(786),
 'okay': np.int64(1472),
 'weekend': np.int64(2367),
 'leh': np.int64(1115),
 'unsubscrib': np.int64(2226),
 'mob': np.int64(1307),
 'term': np.int64(2062),
 'themob': np.int64(2088),
 'help': np.int64(901),
 'info': np.int64(1000),
 'half': np.int64(877),
 'hour': np.int64(950),
 'half hour': np.int64(878),
 'cant': np.int64(276),
 'pick': np.int64(1552),
 'messag': np.int64(1275),
 'cant pick': np.int64(278),
 'pick phone': np.int64(1553),
 'phone right': np.int64(1549),
 'right pl': np.int64(1740),
 'send messag': np.int64(1817),
 'someon': np.int64(1912),
 'guess': np.int64(866),
 'someon know': np.int64(1913),
 'date servic': np.int64(468),
 'alway': np.int64(53),
 'yup': np.int64(2498),
 'thk': np.int64(2099),
 'teacher': np.int64(2049),
 'face': np.int64(637),
 'longer': np.int64(1170),
 'darren': np.int64(465),
 'short': np.int64(1850),
 'noth': np.int64(1437),
 'lar': np.int64(1082),
 'romant': np.int64(1749),
 'bit': np.int64(168),
 'lost': np.int64(1179),
 'hiya': np.int64(917),
 'naughti': np.int64(1382),
 'bought': np.int64(194),
 'littl': np.int64(1149),
 'shop': np.int64(1848),
 'tho': np.int64(2101),
 'kind': np.int64(1062),
 'last night': np.int64(1086),
 'load': np.int64(1154),
 'money': np.int64(1329),
 'someth': np.int64(1914),
 'thank god': np.int64(2081),
 'st': np.int64(1954),
 'five': np.int64(682),
 'mon': np.int64(1327),
 'thur': np.int64(2108),
 'book': np.int64(187),
 'best': np.int64(155),
 'wen': np.int64(2378),
 'die': np.int64(510),
 'near': np.int64(1387),
 'bodi': np.int64(182),
 'bcoz': np.int64(142),
 'hand': np.int64(880),
 'may': np.int64(1254),
 'tear': np.int64(2051),
 'gud': np.int64(861),
 'ni': np.int64(1411),
 'gud ni': np.int64(864),
 'guy': np.int64(868),
 'close': np.int64(346),
 'num': np.int64(1443),
 'thanx': np.int64(2084),
 'ok lor': np.int64(1464),
 'omg': np.int64(1475),
 'could': np.int64(422),
 'snow': np.int64(1906),
 'tonit': np.int64(2151),
 'loan': np.int64(1155),
 'sunday': np.int64(2012),
 'holiday': np.int64(928),
 'depend': np.int64(503),
 'qualiti': np.int64(1653),
 'type': np.int64(2206),
 'mayb': np.int64(1256),
 'serious': np.int64(1829),
 'word': np.int64(2424),
 'dinner': np.int64(518),
 'parti': np.int64(1517),
 'bold': np.int64(183),
 'wors': np.int64(2432),
 'better': np.int64(158),
 'complet': np.int64(384),
 'goodmorn': np.int64(819),
 'pain': np.int64(1510),
 'goodmorn today': np.int64(820),
 'today late': np.int64(2136),
 'parent': np.int64(1512),
 'colleagu': np.int64(359),
 'scream': np.int64(1790),
 'surpris': np.int64(2025),
 'nake': np.int64(1374),
 'seri': np.int64(1827),
 'mean': np.int64(1258),
 'record': np.int64(1697),
 'ha': np.int64(870),
 'tonight': np.int64(2149),
 'haf': np.int64(872),
 'smth': np.int64(1904),
 'mind': np.int64(1290),
 'spoke': np.int64(1949),
 'satisfi': np.int64(1775),
 'experi': np.int64(629),
 'like know': np.int64(1137),
 'sign': np.int64(1864),
 'matur': np.int64(1249),
 'actual': np.int64(18),
 'understand': np.int64(2220),
 'small': np.int64(1895),
 'bslvyl': np.int64(212),
 'grand': np.int64(836),
 'cover': np.int64(426),
 'probabl': np.int64(1637),
 'first': np.int64(680),
 'life': np.int64(1130),
 'space': np.int64(1935),
 'rememb': np.int64(1710),
 'around': np.int64(89),
 'move': np.int64(1342),
 'key': np.int64(1057),
 'escap': np.int64(602),
 'theatr': np.int64(2087),
 'go watch': np.int64(800),
 'bring': np.int64(208),
 'light': np.int64(1132),
 'everyon': np.int64(617),
 'project': np.int64(1640),
 'lucki': np.int64(1206),
 'credit': np.int64(433),
 'card': np.int64(282),
 'ga': np.int64(742),
 'told': np.int64(2140),
 'chat': np.int64(316),
 'awesom': np.int64(122),
 'unless': np.int64(2222),
 'tot': np.int64(2155),
 'group': np.int64(845),
 'mate': np.int64(1245),
 'havent': np.int64(891),
 'wat': np.int64(2340),
 'wat time': np.int64(2343),
 'kate': np.int64(1051),
 'ring': np.int64(1741),
 'asap': np.int64(92),
 'hi hi': np.int64(912),
 'problem': np.int64(1638),
 'spend': np.int64(1946),
 'return': np.int64(1733),
 'mani happi': np.int64(1235),
 'happi return': np.int64(888),
 'return day': np.int64(1734),
 'wish happi': np.int64(2405),
 'fyi': np.int64(741),
 'ride': np.int64(1738),
 'earli': np.int64(568),
 'place': np.int64(1569),
 'hmm': np.int64(921),
 'obvious': np.int64(1451),
 'cake': np.int64(234),
 'fun': np.int64(738),
 'lovabl': np.int64(1182),
 'bcum': np.int64(143),
 'angri': np.int64(59),
 'wid': np.int64(2391),
 'dnt': np.int64(528),
 'coz': np.int64(427),
 'childish': np.int64(326),
 'true': np.int64(2174),
 'show': np.int64(1853),
 'deep': np.int64(492),
 'affect': np.int64(29),
 'nice day': np.int64(1413),
 'day da': np.int64(471),
 'auction': np.int64(105),
 'brand': np.int64(203),
 'brand new': np.int64(204),
 'new nokia': np.int64(1404),
 'free join': np.int64(711),
 'txt nokia': np.int64(2193),
 'ok said': np.int64(1468),
 'bonu': np.int64(184),
 'attempt': np.int64(101),
 'reach': np.int64(1679),
 'bonu caller': np.int64(185),
 'caller prize': np.int64(261),
 'prize nd': np.int64(1635),
 'nd attempt': np.int64(1384),
 'attempt reach': np.int64(103),
 'reach call': np.int64(1680),
 'call asap': np.int64(237),
 'pa': np.int64(1505),
 'knw': np.int64(1070),
 'ru': np.int64(1760),
 'song': np.int64(1918),
 'dun': np.int64(562),
 'open': np.int64(1485),
 'surf': np.int64(2024),
 'plan': np.int64(1570),
 'valentin': np.int64(2282),
 'url': np.int64(2271),
 'tell friend': np.int64(2057),
 'valentin day': np.int64(2283),
 'shower': np.int64(1857),

### Train The model

In [41]:
from sklearn.naive_bayes import MultinomialNB # Multinomial Naive Bayes

In [42]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [43]:
y_pred=spam_detect_model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,classification_report

In [45]:
accuracy_score(y_test,y_pred)

0.9829596412556054

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.96      0.90      0.93       141
        True       0.99      0.99      0.99       974

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

### Creating The TF-IDF Model

In [47]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [49]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0.143, 0, 0.221, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.402, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0.295, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.309, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0.212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.587, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.411, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.539, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.51, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0.494, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.447, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.315, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], shape=(4457, 2500))

In [50]:
tv.vocabulary_

{'enjoy': np.int64(611),
 'shower': np.int64(1890),
 'possess': np.int64(1641),
 'ur': np.int64(2239),
 'love': np.int64(1217),
 'one': np.int64(1513),
 'bcoz': np.int64(152),
 'world': np.int64(2431),
 'lie': np.int64(1164),
 'gift': np.int64(798),
 'truli': np.int64(2188),
 'ur love': np.int64(2251),
 'love one': np.int64(1225),
 'today': np.int64(2146),
 'offer': np.int64(1487),
 'claim': np.int64(347),
 'worth': np.int64(2436),
 'discount': np.int64(543),
 'voucher': np.int64(2309),
 'text': np.int64(2090),
 'ye': np.int64(2474),
 'savamob': np.int64(1817),
 'member': np.int64(1302),
 'mobil': np.int64(1348),
 'cs': np.int64(457),
 'sub': np.int64(2029),
 'unsub': np.int64(2231),
 'repli': np.int64(1752),
 'claim ur': np.int64(352),
 'ur worth': np.int64(2262),
 'worth discount': np.int64(2437),
 'discount voucher': np.int64(544),
 'text ye': np.int64(2098),
 'ye savamob': np.int64(2476),
 'savamob member': np.int64(1818),
 'member offer': np.int64(1303),
 'offer mobil': np.int64(1489),
 'mobil cs': np.int64(1352),
 'txting': np.int64(2215),
 'drive': np.int64(575),
 'leav': np.int64(1146),
 'around': np.int64(94),
 'ok': np.int64(1497),
 'yo': np.int64(2492),
 'game': np.int64(769),
 'almost': np.int64(52),
 'want': np.int64(2326),
 'go': np.int64(812),
 'soon': np.int64(1954),
 'want go': np.int64(2329),
 'got': np.int64(851),
 'thing': np.int64(2110),
 'may': np.int64(1287),
 'pub': np.int64(1685),
 'later': np.int64(1124),
 'come': np.int64(387),
 'home': np.int64(967),
 'half': np.int64(908),
 'hour': np.int64(985),
 'come ur': np.int64(395),
 'ur home': np.int64(2247),
 'half hour': np.int64(909),
 'oh': np.int64(1494),
 'forward': np.int64(726),
 'messag': np.int64(1308),
 'thought': np.int64(2121),
 'send': np.int64(1851),
 'forward messag': np.int64(727),
 'yar': np.int64(2471),
 'yest': np.int64(2487),
 'late': np.int64(1123),
 'alreadi': np.int64(54),
 'se': np.int64(1830),
 'ask': np.int64(102),
 'lor': np.int64(1208),
 'still': np.int64(1999),
 'act': np.int64(13),
 'real': np.int64(1720),
 'ask go': np.int64(104),
 'sport': np.int64(1979),
 'type': np.int64(2218),
 'told': np.int64(2153),
 'wednesday': np.int64(2355),
 'sorri': np.int64(1957),
 'free': np.int64(731),
 'new': np.int64(1433),
 'year': np.int64(2482),
 'eve': np.int64(629),
 'went': np.int64(2376),
 'parti': np.int64(1554),
 'si': np.int64(1892),
 'hey': np.int64(941),
 'new year': np.int64(1438),
 'min': np.int64(1318),
 'india': np.int64(1033),
 'sed': np.int64(1837),
 'er': np.int64(622),
 'bill': np.int64(173),
 'dont': np.int64(558),
 'giv': np.int64(803),
 'shit': np.int64(1882),
 'due': np.int64(580),
 'day': np.int64(488),
 'wine': np.int64(2400),
 'never': np.int64(1432),
 'bitch': np.int64(180),
 'tri': np.int64(2180),
 'give': np.int64(804),
 'drug': np.int64(578),
 'answer': np.int64(69),
 'fuck': np.int64(759),
 'phone': np.int64(1580),
 'juz': np.int64(1078),
 'rememb': np.int64(1745),
 'gotta': np.int64(858),
 'bath': np.int64(148),
 'dog': np.int64(554),
 'wonder': np.int64(2421),
 'th': np.int64(2100),
 'style': np.int64(2026),
 'smile': np.int64(1929),
 'person': np.int64(1574),
 'rd': np.int64(1712),
 'natur': np.int64(1417),
 'nd': np.int64(1420),
 'sm': np.int64(1924),
 'st': np.int64(1982),
 'friendship': np.int64(752),
 'good': np.int64(836),
 'morn': np.int64(1374),
 'dear': np.int64(501),
 'wonder world': np.int64(2422),
 'world th': np.int64(2432),
 'th th': np.int64(2101),
 'th ur': np.int64(2102),
 'ur style': np.int64(2261),
 'style th': np.int64(2027),
 'ur smile': np.int64(2259),
 'smile th': np.int64(1931),
 'ur person': np.int64(2256),
 'person rd': np.int64(1576),
 'rd ur': np.int64(1713),
 'ur natur': np.int64(2255),
 'natur nd': np.int64(1418),
 'nd ur': np.int64(1422),
 'ur sm': np.int64(2258),
 'sm st': np.int64(1927),
 'st ur': np.int64(1984),
 'love friendship': np.int64(1219),
 'friendship good': np.int64(753),
 'good morn': np.int64(843),
 'morn dear': np.int64(1376),
 'copi': np.int64(432),
 'da': np.int64(475),
 'report': np.int64(1758),
 'wat': np.int64(2337),
 'make': np.int64(1255),
 'peopl': np.int64(1565),
 'de': np.int64(498),
 'happi': np.int64(917),
 'dat': np.int64(485),
 'feel': np.int64(677),
 'meet': np.int64(1297),
 'pain': np.int64(1549),
 'miss': np.int64(1333),
 'work': np.int64(2427),
 'ah': np.int64(38),
 'den': np.int64(520),
 'plu': np.int64(1617),
 'workin': np.int64(2430),
 'oso': np.int64(1539),
 'rite': np.int64(1781),
 'orchard': np.int64(1534),
 'place': np.int64(1605),
 'liao': np.int64(1161),
 'den go': np.int64(521),
 'yay': np.int64(2473),
 'wait': np.int64(2314),
 'togeth': np.int64(2152),
 'great': np.int64(865),
 'lol': np.int64(1197),
 'realli': np.int64(1723),
 'need': np.int64(1424),
 'eat': np.int64(592),
 'drink': np.int64(574),
 'appreci': np.int64(84),
 'keep': np.int64(1083),
 'compani': np.int64(399),
 'night': np.int64(1446),
 'babe': np.int64(133),
 'print': np.int64(1669),
 'forum': np.int64(725),
 'post': np.int64(1643),
 'guy': np.int64(900),
 'exact': np.int64(641),
 'prob': np.int64(1678),
 'fix': np.int64(705),
 'hope': np.int64(972),
 'ignor': np.int64(1015),
 'haha': np.int64(905),
 'yeah': np.int64(2478),
 'oz': np.int64(1543),
 'kind': np.int64(1096),
 'let': np.int64(1158),
 'know': np.int64(1102),
 'anyth': np.int64(73),
 'els': np.int64(598),
 'someth': np.int64(1946),
 'mani': np.int64(1265),
 'beer': np.int64(163),
 'shall': np.int64(1876),
 'get': np.int64(784),
 'let know': np.int64(1159),
 'anyth els': np.int64(74),
 'done': np.int64(557),
 'even': np.int64(630),
 'sir': np.int64(1907),
 'al': np.int64(47),
 'share': np.int64(1878),
 'news': np.int64(1439),
 'god': np.int64(828),
 'join': np.int64(1068),
 'fine': np.int64(699),
 'allah': np.int64(50),
 'sometim': np.int64(1949),
 'rakhesh': np.int64(1700),
 'good even': np.int64(840),
 'yup': np.int64(2498),
 'fool': np.int64(719),
 'cheat': np.int64(332),
 'other': np.int64(1540),
 'say': np.int64(1822),
 'pleas': np.int64(1612),
 'take': np.int64(2060),
 'go take': np.int64(825),
 'jay': np.int64(1063),
 'tell': np.int64(2080),
 'littl': np.int64(1183),
 'track': np.int64(2174),
 'idea': np.int64(1010),
 'smoke': np.int64(1932),
 'much': np.int64(1398),
 'month': np.int64(1369),
 'smoke much': np.int64(1933),
 'lt': np.int64(1233),
 'gt': np.int64(875),
 'pple': np.int64(1649),
 'marri': np.int64(1272),
 'lover': np.int64(1228),
 'hav': np.int64(925),
 'gud': np.int64(893),
 'avoid': np.int64(121),
 'problem': np.int64(1680),
 'sent': np.int64(1858),
 'di': np.int64(527),
 'wil': np.int64(2393),
 'friday': np.int64(748),
 'like': np.int64(1170),
 'tomorrow': np.int64(2155),
 'best': np.int64(167),
 'life': np.int64(1165),
 'break': np.int64(215),
 'frnd': np.int64(755),
 'read': np.int64(1717),
 'lt gt': np.int64(1235),
 'send lt': np.int64(1853),
 'gt min': np.int64(882),
 'call': np.int64(246),
 'sorri call': np.int64(1958),
 'call later': np.int64(260),
 'left': np.int64(1148),
 'said': np.int64(1807),
 'would': np.int64(2439),
 'inform': np.int64(1038),
 'account': np.int64(8),
 'rent': np.int64(1749),
 'discuss': np.int64(545),
 'hous': np.int64(986),
 'anoth': np.int64(67),
 'check': np.int64(333),
 'onlin': np.int64(1518),
 'said would': np.int64(1811),
 'hear': np.int64(929),
 'omg': np.int64(1511),
 'provid': np.int64(1684),
 'thank': np.int64(2103),
 'good hear': np.int64(841),
 'miss much': np.int64(1337),
 'mth': np.int64(1395),
 'price': np.int64(1663),
 'orang': np.int64(1531),
 'line': np.int64(1175),
 'rental': np.int64(1750),
 'latest': np.int64(1127),
 'camera': np.int64(285),
 'updat': np.int64(2234),
 'stoptxt': np.int64(2014),
 'half price': np.int64(910),
 'price orang': np.int64(1666),
 'orang line': np.int64(1532),
 'line rental': np.int64(1177),
 'latest camera': np.int64(1128),
 'camera phone': np.int64(289),
 'phone free': np.int64(1583),
 'hiya': np.int64(950),
 'wot': np.int64(2438),
 'im': np.int64(1018),
 'moment': np.int64(1365),
 'hate': np.int64(924),
 'hell': np.int64(936),
 'wont': np.int64(2423),
 'luv': np.int64(1246),
 'neva': np.int64(1431),
 'noe': np.int64(1453),
 'aft': np.int64(32),
 'wow': np.int64(2441),
 'boy': np.int64(213),
 'back': np.int64(136),
 'uk': np.int64(2221),
 'tour': np.int64(2171),
 'win': np.int64(2394),
 'ticket': np.int64(2129),
 'book': np.int64(198),
 'club': np.int64(361),
 'txt': np.int64(2205),
 'ltd': np.int64(1237),
 'info': np.int64(1037),
 'select': np.int64(1846),
 'content': np.int64(424),
 'tone': np.int64(2156),
 'wap': np.int64(2335),
 'cream': np.int64(451),
 'actual': np.int64(16),
 'full': np.int64(760),
 'msg': np.int64(1390),
 'hurri': np.int64(1002),
 'privat': np.int64(1670),
 'statement': np.int64(1993),
 'privat account': np.int64(1671),
 'account statement': np.int64(9),
 'polic': np.int64(1635),
 'station': np.int64(1995),
 'noth': np.int64(1472),
 'week': np.int64(2357),
 'entri': np.int64(618),
 'textpod': np.int64(2099),
 'chanc': np.int64(321),
 'gb': np.int64(775),
 'ipod': np.int64(1050),
 'cash': np.int64(306),
 'everi': np.int64(633),
 'wk': np.int64(2413),
 'ts': np.int64(2192),
 'www': np.int64(2451),
 'net': np.int64(1427),
 'custcar': np.int64(466),
 'free st': np.int64(742),
 'st week': np.int64(1985),
 'chanc win': np.int64(323),
 'gb ipod': np.int64(776),
 'cash everi': np.int64(310),
 'everi wk': np.int64(636),
 'wk txt': np.int64(2414),
 'ts cs': np.int64(2193),
 'cs www': np.int64(460),
 'ill': np.int64(1017),
 'pa': np.int64(1544),
 'model': np.int64(1363),
 'pl': np.int64(1597),
 'mail': np.int64(1254),
 'id': np.int64(1009),
 'pl send': np.int64(1604),
 'ya': np.int64(2467),
 'better': np.int64(169),
 'tho': np.int64(2119),
 'daddi': np.int64(479),
 'scream': np.int64(1829),
 'pleasur': np.int64(1615),
 'ass': np.int64(108),
 'glad': np.int64(807),
 'treat': np.int64(2179),
 'urself': np.int64(2274),
 'cam': np.int64(279),
 'pm': np.int64(1620),
 'someon': np.int64(1942),
 'contact': np.int64(417),
 'date': np.int64(486),
 'servic': np.int64(1865),
 'enter': np.int64(614),
 'fanci': np.int64(663),
 'find': np.int64(694),
 'landlin': np.int64(1114),
 'pobox': np.int64(1626),
 'contact date': np.int64(419),
 'date servic': np.int64(487),
 'find call': np.int64(695),
 'call landlin': np.int64(259),
 'ni': np.int64(1442),
 'well': np.int64(2371),
 'care': np.int64(300),
 'swt': np.int64(2056),
 'dream': np.int64(572),
 'gud ni': np.int64(896),
 'well take': np.int64(2373),
 'take care': np.int64(2061),
 'swt dream': np.int64(2057),
 'burn': np.int64(233),
 'nokia': np.int64(1454),
 'camcord': np.int64(280),
 'deliveri': np.int64(517),
 'tri call': np.int64(2181),
 'call repli': np.int64(267),
 'nokia mobil': np.int64(1459),
 'mobil free': np.int64(1354),
 'free camcord': np.int64(735),
 'pleas call': np.int64(1613),
 'call deliveri': np.int64(251),
 'deliveri tomorrow': np.int64(518),
 'mean': np.int64(1291),
 'look': np.int64(1203),
 'time': np.int64(2132),
 'learn': np.int64(1144),
 'lesson': np.int64(1157),
 'ok go': np.int64(1498),
 'go home': np.int64(818),
 'video': np.int64(2292),
 'unlimit': np.int64(2230),
 'text free': np.int64(2094),
 'camcord repli': np.int64(281),
 'repli call': np.int64(1753),
 'big': np.int64(172),
 'brother': np.int64(220),
 'social': np.int64(1936),
 'sure': np.int64(2049),
 'process': np.int64(1681),
 'direct': np.int64(539),
 'pay': np.int64(1560),
 'way': np.int64(2345),
 'test': np.int64(2089),
 'class': np.int64(355),
 'find way': np.int64(698),
 'buy': np.int64(235),
 'space': np.int64(1967),
 'arcad': np.int64(87),
 'press': np.int64(1660),
 'std': np.int64(1997),
 'charg': np.int64(326),
 'see': np.int64(1839),
 'co': np.int64(364),
 'term': np.int64(2087),
 'set': np.int64(1869),
 'purchas': np.int64(1686),
 'co uk': np.int64(366),
 'right': np.int64(1775),
 'outsid': np.int64(1542),
 'hard': np.int64(922),
 'live': np.int64(1184),
 'chat': np.int64(329),
 'choos': np.int64(341),
 'girl': np.int64(801),
 'connect': np.int64(415),
 'cheap': np.int64(330),
 'wc': np.int64(2349),
 'xx': np.int64(2464),
 'wc xx': np.int64(2350),
 'didnt': np.int64(529),
 'tonight': np.int64(2161),
 'whenev': np.int64(2382),
 'cool': np.int64(430),
 'cool text': np.int64(431),
 'train': np.int64(2175),
 'colleg': np.int64(379),
 'lar': np.int64(1118),
 'sleep': np.int64(1919),
 'earli': np.int64(587),
 'nite': np.int64(1451),
 'ok lar': np.int64(1499),
 'tv': np.int64(2201),
 'quiz': np.int64(1693),
 'flower': np.int64(714),
 'win cash': np.int64(2395),
 'think': np.int64(2111),
 'thk': np.int64(2117),
 'em': np.int64(599),
 'far': np.int64(668),
 'goin': np.int64(832),
 'rest': np.int64(1767),
 'dunno': np.int64(584),
 'yet': np.int64(2489),
 'dinner': np.int64(537),
 'might': np.int64(1315),
 'abl': np.int64(2),
 'sun': np.int64(2039),
 'bird': np.int64(175),
 'wish': np.int64(2403),
 'goodmorn': np.int64(847),
 'amp': np.int64(61),
 'nice': np.int64(1443),
 'nice day': np.int64(1444),
 'gr': np.int64(859),
 'congrat': np.int64(411),
 'school': np.int64(1827),
 'plan': np.int64(1606),
 'wat ur': np.int64(2339),
 'food': np.int64(718),
 'fat': np.int64(670),
 'ex': np.int64(640),
 'urgent': np.int64(2266),
 'pl call': np.int64(1598),
 'wrong': np.int64(2446),
 'number': np.int64(1479),
 'put': np.int64(1688),
 'pick': np.int64(1588),
 'us': np.int64(2275),
 'hi': np.int64(945),
 'darlin': np.int64(483),
 'troubl': np.int64(2185),
 'talk': np.int64(2064),
 'mum': np.int64(1399),
 'last': np.int64(1119),
 'realli good': np.int64(1724),
 'good time': np.int64(845),
 'last night': np.int64(1120),
 'pizza': np.int64(1596),
 'reach': np.int64(1714),
 'happen': np.int64(915),
 'blackberri': np.int64(184),
 'bold': np.int64(194),
 'torch': np.int64(2166),
 'use': np.int64(2276),
 'say lt': np.int64(1825),
 'worri': np.int64(2433),
 'stay': np.int64(1996),
 'eh': np.int64(596),
 'leh': np.int64(1150),
 'din': np.int64(535),
 'sad': np.int64(1801),
 'watch': np.int64(2340),
 'offic': np.int64(1491),
 'watch tv': np.int64(2343),
 'get back': np.int64(785),
 'damn': np.int64(481),
 'poor': np.int64(1638),
 'stand': np.int64(1987),
 'ok lor': np.int64(1500),
 'christma': np.int64(342),
 'celebr': np.int64(319),
 'valu': np.int64(2286),
 'affect': np.int64(30),
 'stupid': np.int64(2025),
 'possibl': np.int64(1642),
 'teacher': np.int64(2074),
 'teach': np.int64(2073),
 'exam': np.int64(643),
 'first': np.int64(702),
 'cant': np.int64(294),
 'dirti': np.int64(542),
 'sex': np.int64(1872),
 'man': np.int64(1260),
 'cant wait': np.int64(297),
 'show': np.int64(1887),
 'bonu': np.int64(195),
 'point': np.int64(1630),
 'identifi': np.int64(1011),
 'code': np.int64(367),
 'expir': np.int64(652),
 'statement show': np.int64(1994),
 'point claim': np.int64(1632),
 'claim call': np.int64(348),
 'call identifi': np.int64(256),
 'identifi code': np.int64(1012),
 'code expir': np.int64(368),
 'aight': np.int64(42),
 'comin': np.int64(396),
 'armand': np.int64(93),
 'differ': np.int64(531),
 'walk': np.int64(2318),
 'without': np.int64(2411),
 'askin': np.int64(107),
 'laugh': np.int64(1134),
 'sunday': np.int64(2040),
 'holiday': np.int64(962),
 'bring': np.int64(218),
 'med': np.int64(1294),
 'took': np.int64(2164),
 'die': np.int64(530),
 'listen': np.int64(1182),
 'total': np.int64(2168),
 'mp': np.int64(1383),
 'wan': np.int64(2319),
 'wan come': np.int64(2320),
 'thinkin': np.int64(2116),
 'gettin': np.int64(795),
 'bit': np.int64(179),
 'mo': np.int64(1344),
 'sister': np.int64(1909),
 'law': np.int64(1135),
 'abiola': np.int64(1),
 'hope great': np.int64(976),
 'get ur': np.int64(793),
 'goe': np.int64(830),
 'friend': np.int64(749),
 'imma': np.int64(1020),
 'vodafon': np.int64(2305),
 'end': np.int64(603),
 'receiv': np.int64(1727),
 'award': np.int64(125),
 'match': np.int64(1275),
 'number end': np.int64(1481),
 'end select': np.int64(604),
 'select receiv': np.int64(1847),
 'receiv award': np.int64(1728),
 'coupl': np.int64(442),
 'buck': np.int64(228),
 'love ya': np.int64(1227),
 'finish': np.int64(701),
 'next': np.int64(1440),
 'amaz': np.int64(59),
 'xxx': np.int64(2465),
 'enough': np.int64(613),
 'text back': np.int64(2091),
 'expect': np.int64(649),
 'mine': np.int64(1327),
 'tomo': np.int64(2154),
 'normal': np.int64(1470),
 'doin': np.int64(555),
 'age': np.int64(36),
 'ring': np.int64(1777),
 'sat': np.int64(1815),
 'complet': np.int64(401),
 'promis': np.int64(1683),
 'per': np.int64(1566),
 'request': np.int64(1761),
 'mell': np.int64(1301),
 'callertun': np.int64(277),
 'caller': np.int64(274),
 'per request': np.int64(1571),
 'set callertun': np.int64(1870),
 'callertun caller': np.int64(278),
 'caller press': np.int64(275),
 'press copi': np.int64(1661),
 'copi friend': np.int64(433),
 'friend callertun': np.int64(750),
 'anyon': np.int64(72),
 'except': np.int64(645),
 'love much': np.int64(1224),
 'dont want': np.int64(561),
 'cuddl': np.int64(461),
 'lot': np.int64(1215),
 'tea': np.int64(2072),
 'vl': np.int64(2302),
 'til': np.int64(2130),
 'dont worri': np.int64(562),
 'futur': np.int64(765),
 'result': np.int64(1768),
 'present': np.int64(1659),
 'face': np.int64(657),
 'choic': np.int64(340),
 'coin': np.int64(372),
 'becoz': np.int64(159),
 'settl': np.int64(1871),
 'question': np.int64(1690),
 'air': np.int64(43),
 'heart': np.int64(931),
 'lost': np.int64(1214),
 'jst': np.int64(1074),
 'bin': np.int64(174),
 'earth': np.int64(589),
 'sofa': np.int64(1937),
 'gd': np.int64(778),
 'oop': np.int64(1521),
 'job': np.int64(1066),
 'shock': np.int64(1883),
 'imagin': np.int64(1019),
 'second': np.int64(1834),
 'somewher': np.int64(1950),
 'could': np.int64(440),
 'save': np.int64(1820),
 'alway': np.int64(58),
 'dine': np.int64(536),
 'ladi': np.int64(1110),
 'po': np.int64(1624),
 'gonna': np.int64(834),
 'sale': np.int64(1812),
 'gonna get': np.int64(835),
 'want come': np.int64(2327),
 'come get': np.int64(389),
 'semest': np.int64(1850),
 'happi new': np.int64(920),
 'hope good': np.int64(975),
 'bed': np.int64(160),
 'slept': np.int64(1921),
 'wid': np.int64(2387),
 'old': np.int64(1510),
 'year old': np.int64(2483),
 'town': np.int64(2173),
 'convey': np.int64(426),
 'birthday': np.int64(176),
 'nimya': np.int64(1449),
 'dnt': np.int64(549),
 'forget': np.int64(722),
 'pl convey': np.int64(1599),
 'convey birthday': np.int64(427),
 'birthday wish': np.int64(177),
 'wish nimya': np.int64(2406),
 'nimya pl': np.int64(1450),
 'today birthday': np.int64(2147),
 'guess': np.int64(898),
 'busi': np.int64(234),
 'speak': np.int64(1968),
 'custom': np.int64(467),
 'brought': np.int64(221),
 'box': np.int64(207),
 'skype': np.int64(1917),
 'wit': np.int64(2408),
 'sura': np.int64(2048),
 'ago': np.int64(37),
 'messag sent': np.int64(1310),
 'close': np.int64(360),
 'bought': np.int64(204),
 'yesterday': np.int64(2488),
 'also': np.int64(57),
 'past': np.int64(1559),
 'pl pl': np.int64(1602),
 'pl dont': np.int64(1600),
 'heard': np.int64(930),
 'ho': np.int64(957),
 'word': np.int64(2424),
 'first time': np.int64(703),
 'time use': np.int64(2136),
 'type word': np.int64(2219),
 'italian': np.int64(1058),
 'least': np.int64(1145),
 'wait til': np.int64(2315),
 'havent': np.int64(927),
 'lei': np.int64(1151),
 'mon': np.int64(1366),
 'sexi': np.int64(1873),
 'bun': np.int64(232),
 'ym': np.int64(2491),
 'sexi bun': np.int64(1874),
 'congratul': np.int64(413),
 'cd': np.int64(318),
 'guarante': np.int64(888),
 'wkli': np.int64(2416),
 'draw': np.int64(568),
 'music': np.int64(1404),
 'tnc': np.int64(2142),
 'ldew': np.int64(1138),
 'com': np.int64(384),
 'ppmx': np.int64(1651),
 'congratul ur': np.int64(414),
 'ur award': np.int64(2240),
 'award cd': np.int64(128),
 'voucher gift': np.int64(2310),
 'gift guarante': np.int64(799),
 'free entri': np.int64(738),
 'entri wkli': np.int64(620),
 'wkli draw': np.int64(2417),
 'draw txt': np.int64(571),
 'txt music': np.int64(2208),
 'music tnc': np.int64(1406),
 'tnc www': np.int64(2143),
 'www ldew': np.int64(2454),
 'ldew com': np.int64(1139),
 'com win': np.int64(386),
 'win ppmx': np.int64(2397),

In [51]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train,y_train)

In [52]:

#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [53]:
from sklearn.metrics import accuracy_score, classification_report
score = accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_test,y_pred))

0.9802690582959641
              precision    recall  f1-score   support

       False       1.00      0.84      0.91       137
        True       0.98      1.00      0.99       978

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115